#!/bin/bash

TAG=elk-logstash-index-dev

start() {
IMAGE=hub.psi.unc.edu.ar/dev/elk-logstash-index-dev
docker run -ti --rm \
    --name $TAG \
    --privileged=true \
    -h "$TAG" \
    $IMAGE /bin/bash -c "
	logstash -f /etc/logstash/conf.d/;
        /bin/bash 
    "
#    -v /etc/localtime:/etc/localtime:ro \
#    -p 5044:5044 \
#    -p 514:514 \

}
 
if [[ $1 = "stop" ]]; then
    docker rm -f $TAG
elif [[ $1 = "bash" ]]; then
    docker exec -ti $TAG bash
else
    start
fi
