#!/bin/bash

TAG=elk-redis-dev

start() {
IMAGE=hub.psi.unc.edu.ar/dev/elk-redis-dev
docker run -ti --rm \
    --name $TAG \
    --privileged=true \
    -h "$TAG" \
    -v /etc/localtime:/etc/localtime:ro \
    -p 6379:6379 \
    $IMAGE /bin/bash -c "
	redis-server /usr/local/etc/redis/redis.conf  &
	/bin/bash
    "
}

if [[ $1 = "stop" ]]; then
    docker rm -f $TAG
elif [[ $1 = "bash" ]]; then
    docker exec -ti $TAG bash
else
    start
fi
