#!/bin/bash

TAG=elk-kibana-dev

start() {
IMAGE=hub.psi.unc.edu.ar/dev/elk-kibana-dev
docker run --name $TAG -e ELASTICSEARCH_URL=http://172.17.0.6:9200 -p 5601:5601 -d $IMAGE

#docker run -ti --rm \
#    --name $TAG \
#    --privileged=true \
#    -h "$TAG" \
#    -e ELASTICSEARCH_URL=http://172.17.0.6:9200 \ 
#    -p 5601:5601 \
#    -d $TAG \
#    $IMAGE /bin/bash -c "
#	/bin/bash 
#    "
#    -v /etc/localtime:/etc/localtime:ro \
	
}
 
if [[ $1 = "stop" ]]; then
    docker rm -f $TAG
elif [[ $1 = "bash" ]]; then
    docker exec -ti $TAG bash
else
    start
fi
